version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.0"
    ports:
      - "3308:3308"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    environment:
        MYSQL_DATABASE: "ppmtcourse"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "test"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ROOT_USER: "root"
    networks:
      springboot-mysql-net:

  ppm-tool:
    container_name: ppm-tool-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    links:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: no
  client:
      container_name: ppm-tool-frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      networks:
        springboot-mysql-net:
networks:
  springboot-mysql-net:

volumes:
  persistent: